# Generated by Django 3.2 on 2021-05-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('bed', models.BooleanField(default=False, verbose_name='Quarantine bed')),
                ('oxygen', models.BooleanField(default=False, verbose_name='Oxygen Cylinder')),
                ('plasma', models.BooleanField(default=False, verbose_name='Plasma Donation')),
                ('date', models.DateField()),
            ],
        ),
    ]
