# Generated by Django 3.2 on 2021-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='help',
            name='oxygen',
        ),
        migrations.RemoveField(
            model_name='help',
            name='plasma',
        ),
        migrations.AddField(
            model_name='help',
            name='helpin',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
