# Generated by Django 3.2 on 2021-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210505_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='helpin',
        ),
        migrations.AddField(
            model_name='help',
            name='bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='help',
            name='oxygen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='help',
            name='plasma',
            field=models.BooleanField(default=False),
        ),
    ]
