# Generated by Django 3.2 on 2021-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_nhelp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='address',
        ),
        migrations.RemoveField(
            model_name='help',
            name='address',
        ),
        migrations.RemoveField(
            model_name='nhelp',
            name='address',
        ),
        migrations.RemoveField(
            model_name='oxygen',
            name='address',
        ),
        migrations.RemoveField(
            model_name='plasma',
            name='address',
        ),
        migrations.AddField(
            model_name='bed',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='bed',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='help',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='help',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='nhelp',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='nhelp',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='plasma',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='plasma',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AlterField(
            model_name='bed',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='help',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AlterField(
            model_name='help',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='nhelp',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AlterField(
            model_name='nhelp',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
    ]
